package net.puffish.skillsmod.calculation;

import net.minecraft.resources.Identifier;
import net.puffish.skillsmod.api.calculation.prototype.BuiltinPrototypes;
import net.puffish.skillsmod.api.calculation.prototype.Prototype;
import net.puffish.skillsmod.impl.calculation.prototype.PrototypeImpl;

public final class LegacyBuiltinPrototypes {
	public static void register() {
		registerAlias(
				BuiltinPrototypes.WORLD,
				Identifier.parse("server"),
				Identifier.parse("get_server")
		);
		registerAlias(
				BuiltinPrototypes.WORLD,
				Identifier.parse("time_of_day"),
				Identifier.parse("get_time_of_day")
		);
		registerAlias(
				BuiltinPrototypes.ENTITY,
				Identifier.parse("type"),
				Identifier.parse("get_type")
		);
		registerAlias(
				BuiltinPrototypes.ENTITY,
				Identifier.parse("world"),
				Identifier.parse("get_world")
		);
		registerAlias(
				BuiltinPrototypes.LIVING_ENTITY,
				Identifier.parse("entity"),
				Identifier.parse("as_entity")
		);
		registerAlias(
				BuiltinPrototypes.LIVING_ENTITY,
				Identifier.parse("world"),
				Identifier.parse("get_world")
		);
		registerAlias(
				BuiltinPrototypes.LIVING_ENTITY,
				Identifier.parse("type"),
				Identifier.parse("get_type")
		);
		registerAlias(
				BuiltinPrototypes.LIVING_ENTITY,
				Identifier.parse("max_health"),
				Identifier.parse("get_max_health")
		);
		registerAlias(
				BuiltinPrototypes.LIVING_ENTITY,
				Identifier.parse("health"),
				Identifier.parse("get_health")
		);
		registerAlias(
				BuiltinPrototypes.PLAYER,
				Identifier.parse("living_entity"),
				Identifier.parse("as_living_entity")
		);
		registerAlias(
				BuiltinPrototypes.PLAYER,
				Identifier.parse("entity"),
				Identifier.parse("as_entity")
		);
		registerAlias(
				BuiltinPrototypes.PLAYER,
				Identifier.parse("world"),
				Identifier.parse("get_world")
		);
		registerAlias(
				BuiltinPrototypes.ITEM,
				Identifier.parse("saturation_modifier"),
				Identifier.parse("get_saturation_modifier")
		);
		registerAlias(
				BuiltinPrototypes.ITEM,
				Identifier.parse("nutrition"),
				Identifier.parse("get_nutrition")
		);
		registerAlias(
				BuiltinPrototypes.ITEM_STACK,
				Identifier.parse("item"),
				Identifier.parse("get_item")
		);
		registerAlias(
				BuiltinPrototypes.ITEM_STACK,
				Identifier.parse("count"),
				Identifier.parse("get_count")
		);
		registerAlias(
				BuiltinPrototypes.BLOCK,
				Identifier.parse("hardness"),
				Identifier.parse("get_hardness")
		);
		registerAlias(
				BuiltinPrototypes.BLOCK,
				Identifier.parse("blast_resistance"),
				Identifier.parse("get_blast_resistance")
		);
		registerAlias(
				BuiltinPrototypes.BLOCK_STATE,
				Identifier.parse("block"),
				Identifier.parse("get_block")
		);
		registerAlias(
				BuiltinPrototypes.DAMAGE_SOURCE,
				Identifier.parse("type"),
				Identifier.parse("get_type")
		);
		registerAlias(
				BuiltinPrototypes.DAMAGE_SOURCE,
				Identifier.parse("attacker"),
				Identifier.parse("get_attacker")
		);
		registerAlias(
				BuiltinPrototypes.DAMAGE_SOURCE,
				Identifier.parse("source"),
				Identifier.parse("get_source")
		);
		registerAlias(
				BuiltinPrototypes.STAT,
				Identifier.parse("type"),
				Identifier.parse("get_type")
		);
		registerAlias(
				BuiltinPrototypes.STATUS_EFFECT_INSTANCE,
				Identifier.parse("level"),
				Identifier.parse("get_level")
		);
		registerAlias(
				BuiltinPrototypes.STATUS_EFFECT_INSTANCE,
				Identifier.parse("duration"),
				Identifier.parse("get_duration")
		);
		registerAlias(
				BuiltinPrototypes.ENTITY_ATTRIBUTE_INSTANCE,
				Identifier.parse("value"),
				Identifier.parse("get_value")
		);
		registerAlias(
				BuiltinPrototypes.ENTITY_ATTRIBUTE_INSTANCE,
				Identifier.parse("base_value"),
				Identifier.parse("get_base_value")
		);
	}

	public static void registerAlias(Prototype<?> prototype, Identifier id, Identifier existingId) {
		if (prototype instanceof PrototypeImpl<?> impl) {
			impl.registerAlias(id, existingId);
		}
	}
}
